default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development: &development
  <<: *default
  database: <%= ENV.fetch('RAILS_DATABASE_DATABASE') { 'self_training_dev' } %>
  username: <%= ENV.fetch('RAILS_DATABASE_USERNAME') { 'postgres' } %>
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { 'db' } %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD') { '' } %>

test:
  <<: *development
  database: self_training_test

production: &production
  <<: *default
  database: <%= ENV.fetch('RAILS_DATABASE_DATABASE') { '' } %>
  username: <%= ENV.fetch('RAILS_DATABASE_USERNAME') { '' } %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { '' } %>
